### PR TITLE
feat: swap address search mapbox basemap with vicmap

### PR DESCRIPTION
**Pull request by hgaitanis**
## Description
Swapped the mapbox basemap in the AddressSearchMap component with Vicmap WMS. Did not use the TILED option because there is an issue with the vicmap basemap requests after zooming in to an address (the issue seems to be caused by the bounding box values).
Added zIndex values for all layers in the component to force correct drawing order.
Fixed a CSS bug with the autocomplete container.

## How Has This Been Tested?
Tested in storybook

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist

- [x] The PR title is no longer than 64 characters.
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core

### CODE REVIEW

**Comment by hgaitanis** [comment]
Looks like tests are failing because of these phantom components again. Any update on how to get rid of these?

**Comment by tim-yao** [comment]
> Looks like tests are failing because of these phantom components again. Any update on how to get rid of these?

@hgaitanis it is caused by multiple ripple versions in lock which I have fixed last time. Not sure why it's coming again. Looking now.

**Comment by tim-yao** [comment]
@hgaitanis I think it's your local node_modules. You may need to remove all node_modules in your local project. Before running unit tests. For now, can you please just remove `src/test/__snapshots__/storyshots.test.js.snap` changes in this PR? Then it should be fine. As CI think the changes you added in commit is obsolete.

**Comment by tim-yao** [comment]
@hgaitanis if you have time, can try fix it in https://github.com/dpc-sdp/myvic-components/blob/develop/src/.storybook/config.js#L38 . It loads all stories from `/packages` dir. If you accidentally has node_modules dir inside it. You will pick stories from there as well. We need regex to exclude node_modules dir.

**Pull request merged**
